#!/system/bin/sh
NAME=$1
PASS=$2
echo $NAME $PASS
echo "\"$NAME\"    *    \"$PASS\"    *" > /data/misc/ppp/pap-secrets
echo "*    \"$NAME\"    \"$PASS\"    *" >> /data/misc/ppp/pap-secrets
echo "\"$NAME\"    *    \"$PASS\"    *" > /data/misc/ppp/chap-secrets
echo "*    \"$NAME\"    \"$PASS\"    *" >> /data/misc/ppp/chap-secrets
chmod 555 /data/misc/ppp/pap-secrets
chmod 555 /data/misc/ppp/chap-secrets

